[package]
name = "nero-desktop"
version = "0.1.0"
edition = "2021"

[package.metadata.i18n]
available-locales = ["en"]
default-locale = "en"
load-path = "locales"

[package.metadata.packager]
product-name = "Nero"
identifier = "moe.nero.app"
before-packaging-command = "cargo build --release"
formats = ["app"]
deep-link-protocols = [
    { schemes = ["nero"], name = "moe.nero.app.callback", role = "viewer" },
]

[dependencies]
iced = { git = "https://github.com/iced-rs/iced.git", rev = "3de4514", features = [
    "advanced",
    "image",
    "svg",
    "tokio",
] }
rust-i18n = "4.2.1"

nero-extensions = { git = "https://github.com/nero-app/libnero.git", rev = "d3dd3df" }
nero-media-proxy = { git = "https://github.com/nero-app/libnero.git", rev = "d3dd3df", features = [
    "torrent-librqbit",
] }
anifile = { git = "https://github.com/dacchidocchi/anifile.git", rev = "9d4742d" }
librqbit = "8.1.1"
anyhow = "1.0.104"
nero-file-store = { git = "https://github.com/nero-app/libnero.git", rev = "a7b0302" }

async-trait = "0.1.92"
axum = "0.8.9"
blake3 = "1.8.7"
dirs = "6.0.0"
infer = "0.22.0"
mime = "0.3.17"
mime_guess = "2.0.5"
open = "5.4.2"
percent-encoding = "2.3.2"
reqwest = "0.12.28"
rfd = "0.17.2"
tokio = { version = "1.53.1", features = ["fs", "net", "rt", "sync"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
url = "2.5.8"

[build-dependencies]
iced_lucide = { git = "https://github.com/A-Disruption/iced_lucide", rev = "d7b13e4" }

[profile.dev]
opt-level = 1
debug = "line-tables-only"

[profile.dev.package."*"]
opt-level = 3
