[package]
name = "tauri-plugin-nero-extensions"
version = "0.1.0"
edition = "2024"
links = "tauri-plugin-nero-extensions"

[build-dependencies]
tauri-plugin = { version = "2.5.1", features = ["build"] }

[dependencies]
anyhow.workspace = true
axum = "0.8.6"
libnero = { git = "https://github.com/nero-app/libnero.git", rev = "3094924", features = [
    "torrent",
] }
librqbit = "8.1.1"
nero-media-proxy = { git = "https://github.com/nero-app/libnero.git", rev = "3094924", features = [
    "torrent-librqbit",
] }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tauri = { version = "2", default-features = false }
tauri-plugin-store = { workspace = true }
tokio = { workspace = true, features = ["net"] }
tracing = { workspace = true }
